filesize_format = "kb"
filesize_metric = true
skip_welcome_message = true
disable_table_indexes = false
nonzero_exit_errors = true
table_mode = "other"
pivot_mode = "auto"
ctrlc_exit = false
complete_from_path = true
prompt = "starship prompt"

[color_config]
primitive_int = "green"
primitive_decimal = "c"
primitive_filesize = "u"
primitive_string = "pb"
primitive_line = "yellow"
primitive_columnpath = "cyan"
primitive_pattern = "white"
primitive_boolean = "green"
primitive_date = "cyan"
primitive_duration = "blue"
primitive_range = "purple"
primitive_path = "yellow"
primitive_binary = "cyan"
separator_color = "white"
header_align = "left"
header_color = "cyan"
header_bold = true
index_color = "cyan"
leading_trailing_space_bg = "white"

[line_editor]
max_history_size = 100000
history_duplicates = "ignoreconsecutive"
history_ignore_space = true
completion_type = "circular"
completion_prompt_limit = 100
keyseq_timeout_ms = 500
edit_mode = "vi"
auto_add_history = true
bell_style = "visible"
color_mode = "enabled"
tab_stop = 4

[textview]
term_width = "default"
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "NoWrapping"
use_italics = true
paging_mode = "QuitIfOneScreen"
pager = "less"
theme = "TwoDark"

